// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCCreativeKitSnapMetadata
// Superclass: NSObject
// Address: 0x112c66898

@interface SCCreativeKitSnapMetadata

// Property: kitPluginType; attributes: Tq,R,N,V_kitPluginType
// Property: isSpotlightPostingPermitted; attributes: TB,R,N,V_isSpotlightPostingPermitted
// Property: oAuthClientId; attributes: T@"NSString",R,C,N,V_oAuthClientId
// Property: applicationId; attributes: T@"NSString",R,C,N,V_applicationId
// Property: attachmentUrl; attributes: T@"NSString",R,C,N,V_attachmentUrl
// Property: snapKitCreativeKitProduct; attributes: Tq,R,N,V_snapKitCreativeKitProduct
// Property: creativeKitVersion; attributes: T@"NSString",R,C,N,V_creativeKitVersion
// Property: didDeleteAttachmentUrl; attributes: TB,R,N,V_didDeleteAttachmentUrl
// Property: didDeleteCaption; attributes: TB,R,N,V_didDeleteCaption
// Property: didDeleteSticker; attributes: TB,R,N,V_didDeleteSticker
// Property: lensId; attributes: Tq,R,N,V_lensId
// Property: scannableLensId; attributes: T@"NSString",R,C,N,V_scannableLensId
// Property: creativeKitShareType; attributes: Tq,R,N,V_creativeKitShareType
// Property: creativeKitStickerType; attributes: Tq,R,N,V_creativeKitStickerType
// Property: hasAttachmentUrl; attributes: TB,R,N,V_hasAttachmentUrl
// Property: hasCaption; attributes: TB,R,N,V_hasCaption
// Property: hasLens; attributes: TB,R,N,V_hasLens
// Property: topicList; attributes: T@"NSString",R,C,N,V_topicList
// Property: isUsingAutogeneratedSticker; attributes: TB,R,N,V_isUsingAutogeneratedSticker
// Property: isFromReactNativePlugin; attributes: TB,R,N,V_isFromReactNativePlugin
// Property: requiresIdentityWebview; attributes: TB,R,N,V_requiresIdentityWebview
// Property: snapKitSessionId; attributes: T@"NSString",R,C,N,V_snapKitSessionId
// Property: deepLinkUrl; attributes: T@"NSString",R,C,N,V_deepLinkUrl
// Property: deepLinkHandlingId; attributes: Tq,R,N,V_deepLinkHandlingId
// Property: hasLensLaunchData; attributes: TB,R,N,V_hasLensLaunchData
// Property: isDraggableSticker; attributes: TB,R,N,V_isDraggableSticker
// Property: identifierForVendor; attributes: T@"NSString",R,C,N,V_identifierForVendor
// Property: ipAddress; attributes: T@"NSString",R,C,N,V_ipAddress
// Property: snapAdsId; attributes: T@"NSString",R,C,N,V_snapAdsId

// -[SCCreativeKitSnapMetadata initWithCoder:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b083a6c

// -[SCCreativeKitSnapMetadata initWithKitPluginType:isSpotlightPostingPermitted:oAuthClientId:applicationId:attachmentUrl:snapKitCreativeKitProduct:creativeKitVersion:didDeleteAttachmentUrl:didDeleteCaption:didDeleteSticker:lensId:scannableLensId:creativeKitShareType:creativeKitStickerType:hasAttachmentUrl:hasCaption:hasLens:topicList:isUsingAutogeneratedSticker:isFromReactNativePlugin:requiresIdentityWebview:snapKitSessionId:deepLinkUrl:deepLinkHandlingId:hasLensLaunchData:isDraggableSticker:identifierForVendor:ipAddress:snapAdsId:]
// Type encoding: @200@0:8q16B24@28@36@44q52@60B68B72B76q80@88q96q104B112B116B120@124B132B136B140@144@152q160B168B172@176@184@192
// Implementation: 0x10b083dec

// -[SCCreativeKitSnapMetadata copyWithZone:]
// Type encoding: @24@0:8^{_NSZone=}16
// Implementation: 0x10b084158

// -[SCCreativeKitSnapMetadata encodeWithCoder:]
// Type encoding: v24@0:8@16
// Implementation: 0x10b08417c

// -[SCCreativeKitSnapMetadata hash]
// Type encoding: Q16@0:8
// Implementation: 0x10b0843f8

// -[SCCreativeKitSnapMetadata isEqual:]
// Type encoding: B24@0:8@16
// Implementation: 0x10b084558

// -[SCCreativeKitSnapMetadata kitPluginType]
// Type encoding: q16@0:8
// Implementation: 0x10b0847f8

// -[SCCreativeKitSnapMetadata isSpotlightPostingPermitted]
// Type encoding: B16@0:8
// Implementation: 0x10b084800

// -[SCCreativeKitSnapMetadata oAuthClientId]
// Type encoding: @16@0:8
// Implementation: 0x10b084808

// -[SCCreativeKitSnapMetadata applicationId]
// Type encoding: @16@0:8
// Implementation: 0x10b084810

// -[SCCreativeKitSnapMetadata attachmentUrl]
// Type encoding: @16@0:8
// Implementation: 0x10b084818

// -[SCCreativeKitSnapMetadata snapKitCreativeKitProduct]
// Type encoding: q16@0:8
// Implementation: 0x10b084820

// -[SCCreativeKitSnapMetadata creativeKitVersion]
// Type encoding: @16@0:8
// Implementation: 0x10b084828

// -[SCCreativeKitSnapMetadata didDeleteAttachmentUrl]
// Type encoding: B16@0:8
// Implementation: 0x10b084830

// -[SCCreativeKitSnapMetadata didDeleteCaption]
// Type encoding: B16@0:8
// Implementation: 0x10b084838

// -[SCCreativeKitSnapMetadata didDeleteSticker]
// Type encoding: B16@0:8
// Implementation: 0x10b084840

// -[SCCreativeKitSnapMetadata lensId]
// Type encoding: q16@0:8
// Implementation: 0x10b084848

// -[SCCreativeKitSnapMetadata scannableLensId]
// Type encoding: @16@0:8
// Implementation: 0x10b084850

// -[SCCreativeKitSnapMetadata creativeKitShareType]
// Type encoding: q16@0:8
// Implementation: 0x10b084858

// -[SCCreativeKitSnapMetadata creativeKitStickerType]
// Type encoding: q16@0:8
// Implementation: 0x10b084860

// -[SCCreativeKitSnapMetadata hasAttachmentUrl]
// Type encoding: B16@0:8
// Implementation: 0x10b084868

// -[SCCreativeKitSnapMetadata hasCaption]
// Type encoding: B16@0:8
// Implementation: 0x10b084870

// -[SCCreativeKitSnapMetadata hasLens]
// Type encoding: B16@0:8
// Implementation: 0x10b084878

// -[SCCreativeKitSnapMetadata topicList]
// Type encoding: @16@0:8
// Implementation: 0x10b084880

// -[SCCreativeKitSnapMetadata isUsingAutogeneratedSticker]
// Type encoding: B16@0:8
// Implementation: 0x10b084888

// -[SCCreativeKitSnapMetadata isFromReactNativePlugin]
// Type encoding: B16@0:8
// Implementation: 0x10b084890

// -[SCCreativeKitSnapMetadata requiresIdentityWebview]
// Type encoding: B16@0:8
// Implementation: 0x10b084898

// -[SCCreativeKitSnapMetadata snapKitSessionId]
// Type encoding: @16@0:8
// Implementation: 0x10b0848a0

// -[SCCreativeKitSnapMetadata deepLinkUrl]
// Type encoding: @16@0:8
// Implementation: 0x10b0848a8

// -[SCCreativeKitSnapMetadata deepLinkHandlingId]
// Type encoding: q16@0:8
// Implementation: 0x10b0848b0

// -[SCCreativeKitSnapMetadata hasLensLaunchData]
// Type encoding: B16@0:8
// Implementation: 0x10b0848b8

// -[SCCreativeKitSnapMetadata isDraggableSticker]
// Type encoding: B16@0:8
// Implementation: 0x10b0848c0

// -[SCCreativeKitSnapMetadata identifierForVendor]
// Type encoding: @16@0:8
// Implementation: 0x10b0848c8

// -[SCCreativeKitSnapMetadata ipAddress]
// Type encoding: @16@0:8
// Implementation: 0x10b0848d0

// -[SCCreativeKitSnapMetadata snapAdsId]
// Type encoding: @16@0:8
// Implementation: 0x10b0848d8

// -[SCCreativeKitSnapMetadata .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x10b0848e0

@end
