// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCSnapEditorAdditionalParams
// Superclass: SCValdiMarshallableObject
// Address: 0x112ca0818

@interface SCSnapEditorAdditionalParams

// Property: withAnimated; attributes: T@"NSNumber",&,D,N
// Property: animatedFilterCount; attributes: T@"NSNumber",&,D,N
// Property: withGallery; attributes: T@"NSNumber",&,D,N
// Property: withFriendStory; attributes: T@"NSNumber",&,D,N
// Property: withPublicStory; attributes: T@"NSNumber",&,D,N
// Property: invitedRecipientCount; attributes: T@"NSNumber",&,D,N
// Property: sourcePageSessionId; attributes: T@"NSString",C,D,N
// Property: previewPageSessionId; attributes: T@"NSString",C,D,N
// Property: productMediaType; attributes: T@"NSString",C,D,N
// Property: encryptedGeoData; attributes: T@"NSString",C,D,N
// Property: filterGeoId; attributes: T@"NSString",C,D,N
// Property: filterGeoIdList; attributes: T@"NSString",C,D,N
// Property: filterInfo; attributes: T@"NSString",C,D,N
// Property: filterCTPItemRequestId; attributes: T@"NSString",C,D,N
// Property: geoFilterDynamicContextSources; attributes: T@"NSString",C,D,N
// Property: filterVisual; attributes: T@"NSString",C,D,N
// Property: lagunaUserAgent; attributes: T@"NSString",C,D,N
// Property: lagunaDeviceId; attributes: T@"NSString",C,D,N
// Property: shareChannel; attributes: T@"NSString",C,D,N
// Property: replyCta; attributes: T@"NSString",C,D,N
// Property: inChatSource; attributes: T@"NSString",C,D,N
// Property: triggeringSection; attributes: T@"NSString",C,D,N
// Property: lowLightStatus; attributes: T@"NSString",C,D,N
// Property: hasLabel; attributes: T@"NSNumber",&,D,N
// Property: mediaDuration; attributes: T@"NSNumber",&,D,N
// Property: fullSnapTimeSec; attributes: T@"NSNumber",&,D,N
// Property: segmentTimeSec; attributes: T@"NSNumber",&,D,N
// Property: mediaSources; attributes: T@"NSArray",C,D,N
// Property: cameraSource; attributes: T@"NSString",C,D,N
// Property: finalSelectedMultiCamLayout; attributes: T@"NSString",C,D,N
// Property: spotlightModes; attributes: T@"NSArray",C,D,N
// Property: flashTriggerSource; attributes: T@"NSString",C,D,N
// Property: isTimeline; attributes: T@"NSNumber",&,D,N
// Property: isMultiCam; attributes: T@"NSNumber",&,D,N
// Property: toneModeAdjustedImageDiff; attributes: T@"NSNumber",&,D,N
// Property: toneModeFineTuningValue; attributes: T@"NSNumber",&,D,N
// Property: toneModeSliderValue; attributes: T@"NSNumber",&,D,N
// Property: toneModeToneMappingParams; attributes: T@"NSArray",C,D,N
// Property: sectionType; attributes: T@"NSString",C,D,N
// Property: multiSnapCount; attributes: T@"NSNumber",&,D,N
// Property: multiSnapIndex; attributes: T@"NSNumber",&,D,N
// Property: deletedSegments; attributes: T@"NSString",C,D,N
// Property: hasIndividualCreativeTools; attributes: T@"NSNumber",&,D,N
// Property: multiSnapBundleId; attributes: T@"NSString",C,D,N
// Property: multiSnapPreviewIndex; attributes: T@"NSNumber",&,D,N
// Property: multiSnapOutputCount; attributes: T@"NSNumber",&,D,N
// Property: multiSnapOutputIndex; attributes: T@"NSNumber",&,D,N
// Property: arBarTabSessionId; attributes: T@"NSString",C,D,N
// Property: arBarTabCategoryId; attributes: T@"NSString",C,D,N
// Property: lensOptionId; attributes: T@"NSString",C,D,N
// Property: lensOptionSourceType; attributes: T@"NSString",C,D,N
// Property: lensSource; attributes: T@"NSString",C,D,N
// Property: lensType; attributes: T@"NSString",C,D,N
// Property: faceFrontCameraCount; attributes: T@"NSNumber",&,D,N
// Property: faceBackCameraCount; attributes: T@"NSNumber",&,D,N
// Property: lensIndexCount; attributes: T@"NSNumber",&,D,N
// Property: lensBundleUrl; attributes: T@"NSString",C,D,N
// Property: hasGeoLens; attributes: T@"NSNumber",&,D,N
// Property: hasSponsoredLens; attributes: T@"NSNumber",&,D,N
// Property: snappableFunnelIdAndDepth; attributes: T@"NSString",C,D,N
// Property: lensNamespace; attributes: T@"NSString",C,D,N
// Property: lensCollectionId; attributes: T@"NSString",C,D,N
// Property: lensAdId; attributes: T@"NSString",C,D,N
// Property: lensSponsoredType; attributes: T@"NSString",C,D,N
// Property: rankingId; attributes: T@"NSString",C,D,N
// Property: rankingData; attributes: T@"NSString",C,D,N
// Property: lensExplorerCategoryId; attributes: T@"NSString",C,D,N
// Property: lensPromptId; attributes: T@"NSString",C,D,N
// Property: lensPromptTurnBasedTurnNumber; attributes: T@"NSNumber",&,D,N
// Property: lensPromptTurnBasedIsComplete; attributes: T@"NSNumber",&,D,N
// Property: lensCustomizationId; attributes: T@"NSString",C,D,N
// Property: targetingCampaignId; attributes: T@"NSString",C,D,N
// Property: launchSourceAdId; attributes: T@"NSString",C,D,N
// Property: captionOnPreviewPresentation; attributes: T@"NSNumber",&,D,N
// Property: staticCaptionPlacePositions; attributes: T@"NSString",C,D,N
// Property: staticCaptionWithTagPlacePositions; attributes: T@"NSString",C,D,N
// Property: captionMenuOpen; attributes: T@"NSNumber",&,D,N
// Property: captionPinUseCount; attributes: T@"NSNumber",&,D,N
// Property: captionAnimatedCount; attributes: T@"NSNumber",&,D,N
// Property: creatorTagCount; attributes: T@"NSNumber",&,D,N
// Property: friendedTagCount; attributes: T@"NSNumber",&,D,N
// Property: unverifiedTagCount; attributes: T@"NSNumber",&,D,N
// Property: filterReverse; attributes: T@"NSNumber",&,D,N
// Property: swipeCount; attributes: T@"NSNumber",&,D,N
// Property: startRecordingTimestamp; attributes: T@"NSString",C,D,N
// Property: firstSwipeDirection; attributes: T@"NSString",C,D,N
// Property: lastFilterRenderTime; attributes: T@"NSString",C,D,N
// Property: filterRenderTimes; attributes: T@"NSString",C,D,N
// Property: filterInfoValue; attributes: T@"NSNumber",&,D,N
// Property: filterStreakValue; attributes: T@"NSNumber",&,D,N
// Property: filterRemovalCount; attributes: T@"NSNumber",&,D,N
// Property: filterStreakType; attributes: T@"NSString",C,D,N
// Property: shouldSaveToMemories; attributes: T@"NSNumber",&,D,N
// Property: snapDidSendToChat; attributes: T@"NSNumber",&,D,N
// Property: snapDidSaveAsCopy; attributes: T@"NSNumber",&,D,N
// Property: snapDidSaveToReplace; attributes: T@"NSNumber",&,D,N
// Property: snapIsFromSearch; attributes: T@"NSNumber",&,D,N
// Property: memoriesUserContext; attributes: T@"NSNumber",&,D,N
// Property: visualFilterIsSeen; attributes: T@"NSNumber",&,D,N
// Property: stickerTrackingCount; attributes: T@"NSNumber",&,D,N
// Property: customStickerSelectionCount; attributes: T@"NSNumber",&,D,N
// Property: customStickerSelectionFromRecentCount; attributes: T@"NSNumber",&,D,N
// Property: customStickerFromCutoutCreationCount; attributes: T@"NSNumber",&,D,N
// Property: customStickerFromCutoutDeletionCount; attributes: T@"NSNumber",&,D,N
// Property: bitmojiGeoStickersCount; attributes: T@"NSNumber",&,D,N
// Property: bitmojiGeoStickersFromRecentCount; attributes: T@"NSNumber",&,D,N
// Property: bitmojiGeoStickersList; attributes: T@"NSString",C,D,N
// Property: contextualStickersCount; attributes: T@"NSNumber",&,D,N
// Property: contextualStickersList; attributes: T@"NSString",C,D,N
// Property: unlockableStickerCount; attributes: T@"NSNumber",&,D,N
// Property: unlockableStickerList; attributes: T@"NSString",C,D,N
// Property: gameSnippetStickerCount; attributes: T@"NSNumber",&,D,N
// Property: gameSnippetStickerList; attributes: T@"NSString",C,D,N
// Property: encodedStickers; attributes: T@"NSString",C,D,N
// Property: stickerCanvasId; attributes: T@"NSString",C,D,N
// Property: stickerMenuOpen; attributes: T@"NSNumber",&,D,N
// Property: stickerPinUseCount; attributes: T@"NSNumber",&,D,N
// Property: stickerTimeBasedUseCount; attributes: T@"NSNumber",&,D,N
// Property: stickerBloopCount; attributes: T@"NSNumber",&,D,N
// Property: stickerBloopListIds; attributes: T@"NSArray",C,D,N
// Property: stickerFromCaptionCount; attributes: T@"NSNumber",&,D,N
// Property: audioFilterStyleId; attributes: T@"NSString",C,D,N
// Property: soundToolEffectChanged; attributes: T@"NSNumber",&,D,N
// Property: audioBitrate; attributes: T@"NSNumber",&,D,N
// Property: activeMicrophoneMode; attributes: T@"NSNumber",&,D,N
// Property: preferredMicrophoneMode; attributes: T@"NSNumber",&,D,N
// Property: lastPreferredMicrophoneMode; attributes: T@"NSNumber",&,D,N
// Property: videoMode; attributes: T@"NSString",C,D,N
// Property: drawToolButtonClicked; attributes: T@"NSNumber",&,D,N
// Property: emojiBrushClicked; attributes: T@"NSNumber",&,D,N
// Property: withTimerToolClick; attributes: T@"NSNumber",&,D,N
// Property: soundToolButtonClicked; attributes: T@"NSNumber",&,D,N
// Property: chatReplyAddMoreFriendButtonClicked; attributes: T@"NSNumber",&,D,N
// Property: withMusicAttached; attributes: T@"NSNumber",&,D,N
// Property: gallerySendSource; attributes: T@"NSString",C,D,N
// Property: destinations; attributes: T@"NSString",C,D,N
// Property: galleryMediaType; attributes: T@"NSString",C,D,N
// Property: orientation; attributes: T@"NSString",C,D,N
// Property: entryType; attributes: T@"NSString",C,D,N
// Property: meo; attributes: T@"NSNumber",&,D,N
// Property: hasCreative; attributes: T@"NSNumber",&,D,N
// Property: entryExternalId; attributes: T@"NSString",C,D,N
// Property: galleryCollectionCategory; attributes: T@"NSString",C,D,N
// Property: visitSendToCount; attributes: T@"NSNumber",&,D,N
// Property: clientProcessingType; attributes: T@"NSString",C,D,N
// Property: templateId; attributes: T@"NSString",C,D,N
// Property: collageUCOLensId; attributes: T@"NSString",C,D,N
// Property: memoriesSnapIndexInStory; attributes: T@"NSNumber",&,D,N
// Property: featuredStoryTemplateName; attributes: T@"NSString",C,D,N
// Property: featuredStoryGroupName; attributes: T@"NSString",C,D,N
// Property: videoCreateSessionId; attributes: T@"NSString",C,D,N
// Property: memSessionId; attributes: T@"NSString",C,D,N
// Property: memTabSessionId; attributes: T@"NSString",C,D,N
// Property: viewSource; attributes: T@"NSString",C,D,N
// Property: memTrimmedSourceDurationMs; attributes: T@"NSNumber",&,D,N
// Property: snapCreateTime; attributes: T@"NSString",C,D,N
// Property: correspondentGuidsString; attributes: T@"NSString",C,D,N
// Property: snapcraftStyleId; attributes: T@"NSString",C,D,N
// Property: tapCount; attributes: T@"NSNumber",&,D,N
// Property: filterVenueYOffset; attributes: T@"NSNumber",&,D,N
// Property: geofilterVenueID; attributes: T@"NSString",C,D,N
// Property: hasVenueFilter; attributes: T@"NSNumber",&,D,N
// Property: hasBackgroundFilter; attributes: T@"NSNumber",&,D,N
// Property: groupStoriesSendCount; attributes: T@"NSNumber",&,D,N
// Property: availableGroupStoriesCount; attributes: T@"NSNumber",&,D,N
// Property: availableExpiredGroupStoryCount; attributes: T@"NSNumber",&,D,N
// Property: officialStoriesSendCount; attributes: T@"NSNumber",&,D,N
// Property: sharedStoriesSendCount; attributes: T@"NSNumber",&,D,N
// Property: viewMoreStoriesTapCount; attributes: T@"NSNumber",&,D,N
// Property: reshareItemId; attributes: T@"NSString",C,D,N
// Property: filterStackingButtonAddCount; attributes: T@"NSNumber",&,D,N
// Property: filterStackingButtonRemoveCount; attributes: T@"NSNumber",&,D,N
// Property: autoCreativeFilterId; attributes: T@"NSString",C,D,N
// Property: withFilterPeeking; attributes: T@"NSNumber",&,D,N
// Property: entryId; attributes: T@"NSString",C,D,N
// Property: snapId; attributes: T@"NSString",C,D,N
// Property: mediaFormat; attributes: T@"NSString",C,D,N
// Property: spectaclesContentId; attributes: T@"NSString",C,D,N
// Property: previewExitType; attributes: T@"NSString",C,D,N
// Property: shutterSpeed; attributes: T@"NSNumber",&,D,N
// Property: iso; attributes: T@"NSNumber",&,D,N
// Property: aperture; attributes: T@"NSNumber",&,D,N
// Property: brightness; attributes: T@"NSNumber",&,D,N
// Property: withAdjustingExposure; attributes: T@"NSNumber",&,D,N
// Property: withAdjustingFocus; attributes: T@"NSNumber",&,D,N
// Property: topsnapAdId; attributes: T@"NSString",C,D,N
// Property: topsnapAdRequestClientId; attributes: T@"NSString",C,D,N
// Property: filterSource; attributes: T@"NSString",C,D,N
// Property: withSnapReply; attributes: T@"NSNumber",&,D,N
// Property: navigationAction; attributes: T@"NSString",C,D,N
// Property: withRecoveredMedia; attributes: T@"NSNumber",&,D,N
// Property: recoveredSnap; attributes: T@"NSNumber",&,D,N
// Property: contentLossReason; attributes: T@"NSString",C,D,N
// Property: screenOverlayDataSize; attributes: T@"NSNumber",&,D,N
// Property: isMediaGeneratedByAIMode; attributes: T@"NSNumber",&,D,N
// Property: roleType; attributes: T@"NSString",C,D,N
// Property: magicMomentSliderPosition; attributes: T@"NSNumber",&,D,N
// Property: magicMomentTriedCount; attributes: T@"NSNumber",&,D,N
// Property: magicMomentApplied; attributes: T@"NSNumber",&,D,N
// Property: matchedTrackId; attributes: T@"NSNumber",&,D,N
// Property: repostSourceSnapId; attributes: T@"NSString",C,D,N
// Property: promptRepostChatId; attributes: T@"NSString",C,D,N
// Property: scanSessionId; attributes: T@"NSString",C,D,N
// Property: timelineSegmentIndex; attributes: T@"NSNumber",&,D,N
// Property: smartTemplateEffect; attributes: T@"NSString",C,D,N
// Property: friendsFeedShortcutType; attributes: T@"NSString",C,D,N
// Property: exportOrigin; attributes: T@"NSString",C,D,N
// Property: savingSessionId; attributes: T@"NSString",C,D,N
// Property: previewExportWithCameraRoll; attributes: T@"NSNumber",&,D,N
// Property: previewExportWithGallery; attributes: T@"NSNumber",&,D,N
// Property: musicEnabledAudioMix; attributes: T@"NSNumber",&,D,N
// Property: voiceoverEnabledAudioMix; attributes: T@"NSNumber",&,D,N
// Property: musicMixedVolume; attributes: T@"NSNumber",&,D,N
// Property: baseMediaMixedVolume; attributes: T@"NSNumber",&,D,N
// Property: voiceoverMixedVolume; attributes: T@"NSNumber",&,D,N
// Property: isStreakRestore; attributes: T@"NSNumber",&,D,N
// Property: expiredStreakCount; attributes: T@"NSNumber",&,D,N
// Property: dreamPackId; attributes: T@"NSString",C,D,N
// Property: dreamId; attributes: T@"NSString",C,D,N
// Property: dreamsSessionId; attributes: T@"NSString",C,D,N
// Property: textToSpeechCount; attributes: T@"NSNumber",&,D,N
// Property: textToSpeechFailed; attributes: T@"NSNumber",&,D,N
// Property: hasExternalMedia; attributes: T@"NSNumber",&,D,N
// Property: externalMediaImportMethods; attributes: T@"NSArray",C,D,N
// Property: isAspectRatioButtonActivated; attributes: T@"NSNumber",&,D,N
// Property: importedContentId; attributes: T@"NSString",C,D,N
// Property: lyricsTrackIdInLens; attributes: T@"NSString",C,D,N
// Property: isQuickCut; attributes: T@"NSNumber",&,D,N
// Property: templateSource; attributes: T@"NSString",C,D,N
// Property: withCtlensEffect; attributes: T@"NSNumber",&,D,N
// Property: lensTools; attributes: T@"NSArray",C,D,N
// Property: lensInfo; attributes: T@"NSString",C,D,N
// Property: lensCommonDataList; attributes: T@"NSArray",C,D,N
// Property: soundVisualizerTools; attributes: T@"NSString",C,D,N

// -[SCSnapEditorAdditionalParams init]
// Type encoding: @16@0:8
// Implementation: 0x10b67a170

// +[SCSnapEditorAdditionalParams valdiMarshallableObjectDescriptor]
// Type encoding: {SCValdiMarshallableObjectDescriptor=^{SCValdiMarshallableObjectFieldDescriptor}^*^{SCValdiMarshallableObjectBlockSupport}C}16@0:8
// Implementation: 0x10b67a190

@end
