// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCACreativeKitBaseEvent
// Superclass: SCASnapKitSnapchatEvent
// Address: 0x112d17800

@interface SCACreativeKitBaseEvent


// -[SCACreativeKitBaseEvent setCreativeKitProductType:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bacc324

// -[SCACreativeKitBaseEvent setCreativeKitShareType:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bacc3a0

// -[SCACreativeKitBaseEvent setDeepLinkHandlingId:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bacc41c

// -[SCACreativeKitBaseEvent setDeepLinkUrl:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bacc46c

// -[SCACreativeKitBaseEvent setHasAttachmentUrl:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc480

// -[SCACreativeKitBaseEvent setHasCaption:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc4d0

// -[SCACreativeKitBaseEvent setHasLensData:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc520

// -[SCACreativeKitBaseEvent setHasLensLaunchData:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc570

// -[SCACreativeKitBaseEvent setHasStickerData:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc5c0

// -[SCACreativeKitBaseEvent setIdentifierForVendor:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bacc610

// -[SCACreativeKitBaseEvent setIpAddress:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bacc624

// -[SCACreativeKitBaseEvent setIsDraggableSticker:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc638

// -[SCACreativeKitBaseEvent setIsSpotlightPostingPermitted:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc688

// -[SCACreativeKitBaseEvent setIsUsingAutogeneratedSticker:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bacc6d8

// -[SCACreativeKitBaseEvent setSnapAdsId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bacc728

@end
