var youtubeIframeId = 'sc-youtube-preview-player';
var player;

// https://developers.google.com/youtube/iframe_api_reference
// Duplicate here so we don't have to import youtube api js lib here just for the enum values.
var YouTubePlayerState = {
  UNSTARTED: -1,
  ENDED: 0,
  PLAYING: 1,
  PAUSED: 2,
  BUFFERING: 3,
  CUED: 5,
};

/**
 * @param {string} host
 * @returns {boolean}
 */
function isYouTubeHost(host) {
  return host === 'youtube.com' || host.endsWith('.youtube.com') || host === 'youtube-nocookie.com' || host.endsWith('.youtube-nocookie.com');
}

/**
 * @returns {?HTMLIFrameElement}
 */
function youtubeIframe() {
  var iframe = document.getElementsByTagName('iframe')[0];
  if (!iframe) {
    return null;
  }

  try {
    return isYouTubeHost(new URL(iframe.src).hostname) ? iframe : null;
  } catch (e) {
    return null;
  }
}

/**
 * @param {string} status
 */
function notifyPlaybackStatus(status) {
  window.webkit.messageHandlers.scYouTubePreviewPlayback.postMessage(status);
}

/**
 * @param {YT.OnStateChangeEvent} event
 */
function onPlayerStateChange(event) {
  if (event.data === YouTubePlayerState.PLAYING) {
    notifyPlaybackStatus("playing");
  }
}

function onYouTubeIframeAPIReady() {
  var iframe = youtubeIframe();
  if (!iframe) {
    return;
  }

  if (iframe.id !== youtubeIframeId) {
    iframe.id = youtubeIframeId;
  }

  player = new window.YT.Player(youtubeIframeId, {
    events: {
      onStateChange: onPlayerStateChange,
    },
  });
}

// Here is one example of the html for Youtube generated by URL Previewer:
// <iframe
//   width="200"
//   height="113"
//   src="https://www.youtube.com/embed/VB1B9bkj2xc?feature=oembed&autoplay=1&playsinline=0&fs=0&controls=1&rel=0&iv_load_policy=3&enablejsapi=1"
//   frameborder="0"
//   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
//   referrerpolicy="strict-origin-when-cross-origin"
//   allowfullscreen title="Norway vs France Extended Highlights 🌎🏆 2026 FIFA World Cup™">
// </iframe>
function loadYouTubeIframeApi() {
  var tag = document.createElement('script');
  tag.src = 'https://www.youtube.com/iframe_api';
  document.head.appendChild(tag);
}

function setup() {
  if (youtubeIframe()) {
    loadYouTubeIframeApi();
  }
}

// Flow:
// 1. The page contains one YouTube iframe with enablejsapi=1.
// 2. Once the iframe is present, load YouTube's official IFrame API script.
// 3. The IFrame API calls the global onYouTubeIframeAPIReady function.
// 4. We wrap the iframe with YT.Player and listen for onStateChange.
// 5. When YouTube reports PLAYING, notify the native WKScriptMessageHandler.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', setup);
} else {
  setup();
}
