// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider
// Superclass: NSObject
// Address: 0x112a1e5b8

@interface SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider

// Property: hash; attributes: TQ,R
// Property: superclass; attributes: T#,R
// Property: description; attributes: T@"NSString",R,C
// Property: debugDescription; attributes: T@"NSString",?,R,C
// Property: scanResultViewModels; attributes: T@"SCObservable",R,N

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider initWithNavigationServices:sendToScopeExposer:conversationDestinationParser:textSender:creativeKitWebDataLoader:urlPreviewProvider:simpleContentFetcher:resourceDownloader:]
// Type encoding: @80@0:8@16@24@32@40@48@56@64@72
// Implementation: 0x1051898bc

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider end]
// Type encoding: v16@0:8
// Implementation: 0x105189aa8

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _detachUI]
// Type encoding: v16@0:8
// Implementation: 0x105189b94

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider scanResultViewModels]
// Type encoding: @16@0:8
// Implementation: 0x105189ba0

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider configureWithContext:]
// Type encoding: v24@0:8@16
// Implementation: 0x105189bc8

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _handleSnapcodeMetadata:]
// Type encoding: v24@0:8@16
// Implementation: 0x105189d90

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider loadDeeplinkData:decodedUuid:scannableId:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x105189ef0

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider loadDataForCreativeKitWebV1:decodedUuid:scannableId:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518a044

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider displaySnapcodeResult:attachmentSafeBrowsingURLType:attributionName:publisherBusinessId:showId:deepLinkURL:decodedUuid:scannableId:]
// Type encoding: v80@0:8@16q24@32@40@48@56@64@72
// Implementation: 0x10518a33c

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider didTapAttachToSnapActionWithAttachmentShareMetadata:attributionName:deepLinkURL:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518a9f8

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider handleAttachToSnapWithAttachmentShareMetadata:attributionName:deepLinkURL:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518ac68

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _handleAttachToSnapWithAttachmentShareMetadataForSticker:attributionName:deepLinkURL:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518aff8

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _handleAttachToSnapWithAttachmentShareMetadataForAutogeneratedSticker:attributionName:deepLinkURL:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518b3bc

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider handleSendToChatWithAttachmentShareMetadata:]
// Type encoding: v24@0:8@16
// Implementation: 0x10518b768

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _navigateToCameraWithSticker:attributionName:deepLinkURL:publisherId:]
// Type encoding: v48@0:8@16@24@32@40
// Implementation: 0x10518b8d0

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _sendMessageToRecipients:groups:additionalText:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518baf0

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _sendMessageToSortedRecipients:additionalText:destinationInfo:]
// Type encoding: v40@0:8@16@24@32
// Implementation: 0x10518bd6c

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _handleTextSendResult:conversationIds:]
// Type encoding: v32@0:8q16@24
// Implementation: 0x10518c044

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider legacySendToScopeDidDismiss:selectedItems:]
// Type encoding: v32@0:8@16@24
// Implementation: 0x10518c1a8

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider legacySendToScopeWillSend:sendToSelection:]
// Type encoding: v32@0:8@16@24
// Implementation: 0x10518c1dc

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _didDetachUIWithSendToSelection:]
// Type encoding: v24@0:8@16
// Implementation: 0x10518c2fc

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _didEndFeatureWithSendToSelection:]
// Type encoding: v24@0:8@16
// Implementation: 0x10518c428

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _sendMessageWithSendToSelection:]
// Type encoding: v24@0:8@16
// Implementation: 0x10518c454

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _dismissMatchaSendTo]
// Type encoding: v16@0:8
// Implementation: 0x10518c52c

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _dismissScanScopeIfNeeded]
// Type encoding: v16@0:8
// Implementation: 0x10518c56c

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _createLoggingMetadata]
// Type encoding: @16@0:8
// Implementation: 0x10518c5a4

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider _createAnalyticsCreativeKit]
// Type encoding: @16@0:8
// Implementation: 0x10518c600

// -[SCScanResultsSnapKitDeeplinkSnapcodeViewModelProvider .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x10518c638

@end
