// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCImpalaStoryPlayerPresenterCreator
// Superclass: NSObject
// Address: 0x112aeb6a8

@interface SCImpalaStoryPlayerPresenterCreator

// Property: hash; attributes: TQ,R
// Property: superclass; attributes: T#,R
// Property: description; attributes: T@"NSString",R,C
// Property: debugDescription; attributes: T@"NSString",?,R,C

// -[SCImpalaStoryPlayerPresenterCreator initWithAdPluginProvider:bitmojiImageFetcher:bloopsStorySharingServices:cameraAttachmentOperaPageResolver:circumstanceEngine:contextExperimentService:commerceOperaAttachmentPluginProvider:commerceOperaScreenshopPluginProvider:contentDelivery:contextOperaPluginProvider:creatorSettingsDataFetcher:creatorSettingsDataMutator:creatorSettingsDataTracker:deeplinkSendToScopeExposer:premiumStoryShareSender:premiumStoryConversationResolver:discoverBlizzardLogger:discoverFeedDataFetcher:discoverFeedEventsLogger:discoverFeedInteractionHistoryManager:discoverFeedNotificationPromptHandler:discoverPublisherPagePropertiesManager:ephemeralMediaFactory:grapheneRegistry:impalaOperaLayerViewControllerProviderCreator:impalaPublicProfilePresentationHandler:legacyStoriesTooltipsService:notificationPool:offPlatformLinkGenerationService:onDemandResourceDownloader:remoteStoriesDataProvider:legacySendToScopeLauncher:sendToScopeLauncher:sendToScopeServices:snapchattersSynchronousDataFetcher:snapDocConfigurer:snapDocOperaParser:storiesCachedReadReceiptViewStateProvider:storiesGrapheneMetricsEmitter:storiesMediaCoordinator:storiesSnapReadReceiptCoordinator:longformMediaPrefetcher:userAccountCreationDate:streamingURLProvider:streamingMediaFetcher:featureSettingsService:currentUsername:conversationDestinationParser:storiesBlizzardLogger:customStoriesDataFetcher:storyShareSender:photoPermissionCoordinator:backgroundTaskWrapper:imageDownloader:imageFetchingService:activeVideoPaths:snapVideoFilterFactory:previewURLVideoProvider:lazySnapDocMediaResolver:lazyNotificationsPermissionRequester:notificationOSSettingsRetriever:lazyNetworkConnectivityMonitor:lazyUserTrackedLogger:lazyDiscoverFeedDataMutator:discoverFeedNotificationOptInRequestManager:safetyReportScopeExposer:contentObjectResolver:externalLinkSendingService:adConfigProvider:safeBrowsingAPI:operaSessionScopeExposer:operaSessionScopeServices:saveFriendStoryOperaPluginProvider:discoverOperaPluginCreator:snapProShareMessageSender:subscriptionWorkflowStarter:snapchattersDataFetcher:impalaLegacyServices:saveStoryScopeExposer:deleteStorySnapScopeExposer:deleteStorySnapScopeServices:bloopsReportScopeExposer:boostCoordinator:composerServices:offPlatformShareServices:storiesExperimentServices:temporaryFileWriter:snapDocEditorFactory:genAIOnboardingServices:profilesProvider:spotlightDataFetcher:previewSnapSenderFactory:contentBlocker:playableViewModelGenerator:contentProductPlaybackExposer:contentProductPlaybackScopeServices:pageLauncherServices:galleryStorySaver:spotlightShareSender:spotlightPlatformAnalyticsCreator:standardExternalContentShareScopeExposer:previewFilterDataProviderFactory:musicContentRestrictionServices:shareNotificationService:userBlizzardLogger:crashServices:snapchatterObservableRepository:storiesUsageLogger:remixOperaPluginProvider:unlockableViewTracker:snapchatterUserInfoProvider:playbackMediaResolver:playbackAssetRepositoryFactory:storiesCachedSummaryInfoProvider:creatorsSubscriptionStoreDelegate:]
// Type encoding: @936@0:8@16@24@32@40@48@56@64@72@80@88@96@104@112@120@128@136@144@152@160@168@176@184@192@200@208@216@224@232@240@248@256@264@272@280@288@296@304@312@320@328@336@344@352@360@368@376@384@392@400@408@416@424@432@440@448@456@464@472@480@488@496@504@512@520@528@536@544@552@560@568@576@584@592@600@608@616@624@632@640@648@656@664@672@680@688@696@704@712@720@728@736@744@752@760@768@776@784@792@800@808@816@824@832@840@848@856@864@872@880@888@896@904@912@920@928
// Implementation: 0x10665becc

// -[SCImpalaStoryPlayerPresenterCreator createImpalaStoryPlayerPresenting]
// Type encoding: @16@0:8
// Implementation: 0x10665d43c

// -[SCImpalaStoryPlayerPresenterCreator .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x10665d9a4

@end
