// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: VRZCandidatePlace
// Superclass: GPBMessage
// Address: 0x112b472f0

@interface VRZCandidatePlace

// Property: placeId; attributes: T@"NSString",C,D,N
// Property: categoryWeight; attributes: Td,D,N
// Property: primaryLanguage; attributes: T@"NSString",C,D,N
// Property: secondaryLanguage; attributes: T@"NSString",C,D,N
// Property: categoryId; attributes: T@"NSString",C,D,N
// Property: alternateCategoryIds; attributes: T@"NSString",C,D,N
// Property: parentCategoryId; attributes: T@"NSString",C,D,N
// Property: lat; attributes: Td,D,N
// Property: lng; attributes: Td,D,N
// Property: countryCode; attributes: T@"NSString",C,D,N
// Property: placeAttributesArray; attributes: T@"NSMutableArray",&,D,N
// Property: placeAttributesArray_Count; attributes: TQ,R,D,N
// Property: mapsPlaceQuadId; attributes: T@"NSString",C,D,N
// Property: quadKey; attributes: T@"NSString",C,D,N
// Property: mapsPlaceQuadPlaceCount; attributes: Td,D,N
// Property: totalPlacesInQuadBeforeTruncation; attributes: Ti,D,N
// Property: weekendCheckins; attributes: Td,D,N
// Property: weekdayCheckins; attributes: Td,D,N
// Property: morningCheckins; attributes: Td,D,N
// Property: afternoonCheckins; attributes: Td,D,N
// Property: nightCheckins; attributes: Td,D,N
// Property: residentCheckins; attributes: Td,D,N
// Property: touristCheckins; attributes: Td,D,N
// Property: deltaCheckins; attributes: Td,D,N
// Property: age1317Checkins; attributes: Td,D,N
// Property: age1820Checkins; attributes: Td,D,N
// Property: age2124Checkins; attributes: Td,D,N
// Property: age2534Checkins; attributes: Td,D,N
// Property: age35PlusCheckins; attributes: Td,D,N
// Property: genderMaleCheckins; attributes: Td,D,N
// Property: genderFemaleCheckins; attributes: Td,D,N
// Property: primaryLanguageCheckins; attributes: Td,D,N
// Property: secondaryLanguageCheckins; attributes: Td,D,N
// Property: weekendPlaceviews; attributes: Td,D,N
// Property: weekdayPlaceviews; attributes: Td,D,N
// Property: morningPlaceviews; attributes: Td,D,N
// Property: afternoonPlaceviews; attributes: Td,D,N
// Property: nightPlaceviews; attributes: Td,D,N
// Property: residentPlaceviews; attributes: Td,D,N
// Property: touristPlaceviews; attributes: Td,D,N
// Property: deltaPlaceviews; attributes: Td,D,N
// Property: age1317Placeviews; attributes: Td,D,N
// Property: age1820Placeviews; attributes: Td,D,N
// Property: age2124Placeviews; attributes: Td,D,N
// Property: age2534Placeviews; attributes: Td,D,N
// Property: age35PlusPlaceviews; attributes: Td,D,N
// Property: genderMalePlaceviews; attributes: Td,D,N
// Property: genderFemalePlaceviews; attributes: Td,D,N
// Property: primaryLanguagePlaceviews; attributes: Td,D,N
// Property: secondaryLanguagePlaceviews; attributes: Td,D,N
// Property: placeVisitDurationHrsThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceVisitGenderDurationHrsThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceVisitGenderDurationHrsThirtyDays; attributes: Td,D,N
// Property: age1317PlaceVisitAgeBucketDurationHrsThirtyDays; attributes: Td,D,N
// Property: age1820PlaceVisitAgeBucketDurationHrsThirtyDays; attributes: Td,D,N
// Property: age2124PlaceVisitAgeBucketDurationHrsThirtyDays; attributes: Td,D,N
// Property: age2534PlaceVisitAgeBucketDurationHrsThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceVisitAgeBucketDurationHrsThirtyDays; attributes: Td,D,N
// Property: placeVisitCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceVisitGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceVisitGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceVisitAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceVisitAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceVisitAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceVisitAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceVisitAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeVisitDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceVisitGenderDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceVisitGenderDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceVisitAgeBucketDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceVisitAgeBucketDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceVisitAgeBucketDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceVisitAgeBucketDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceVisitAgeBucketDurationHrsOneHundredEightyDays; attributes: Td,D,N
// Property: placeVisitCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceVisitGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceVisitGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceVisitAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceVisitAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceVisitAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceVisitAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceVisitAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: numOrbisSnapsAvailable; attributes: Td,D,N
// Property: numProviderSnapsAvailable; attributes: Td,D,N
// Property: placeViewCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceViewGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceViewGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeFavoriteCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceFavoriteGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceFavoriteGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceFavoriteAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceFavoriteAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceFavoriteAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceFavoriteAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceFavoriteAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeCheckinCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceCheckinGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceCheckinGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceCheckinAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceCheckinAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceCheckinAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceCheckinAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceCheckinAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeTrayStoryViewCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeTrayStoryViewDurationSecondsThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderDurationSecondsThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: placeProfileStoryViewCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeProfileStoryViewDurationSecondsThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderDurationSecondsThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketDurationSecondsThirtyDays; attributes: Td,D,N
// Property: placeTrayStoryTapCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryTapGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryTapGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeProfileStoryTapCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryTapGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryTapGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeTrayImpressedCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayImpressedGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayImpressedGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceTrayImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceTrayImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceTrayImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceTrayImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeTrayTapCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayTapGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayTapGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceTrayTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceTrayTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceTrayTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceTrayTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayTapAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeContextCardViewCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceContextCardViewGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceContextCardViewGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceContextCardViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceContextCardViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceContextCardViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceContextCardViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceContextCardViewAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeMapImpressedCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceMapImpressedGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceMapImpressedGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceMapImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceMapImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceMapImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceMapImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceMapImpressedAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeActionCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceActionGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceActionGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeIntentionalActionCountThirtyDays; attributes: Td,D,N
// Property: genderFemalePlaceIntentionalActionGenderCountThirtyDays; attributes: Td,D,N
// Property: genderMalePlaceIntentionalActionGenderCountThirtyDays; attributes: Td,D,N
// Property: age1317PlaceIntentionalActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age1820PlaceIntentionalActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2124PlaceIntentionalActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age2534PlaceIntentionalActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: age35PlusPlaceIntentionalActionAgeBucketCountThirtyDays; attributes: Td,D,N
// Property: placeViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeFavoriteCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceFavoriteGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceFavoriteGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceFavoriteAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceFavoriteAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceFavoriteAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceFavoriteAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceFavoriteAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeCheckinCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceCheckinGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceCheckinGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceCheckinAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceCheckinAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceCheckinAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceCheckinAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceCheckinAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeTrayStoryViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeTrayStoryViewDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: placeProfileStoryViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeProfileStoryViewDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketDurationSecondsOneHundredEightyDays; attributes: Td,D,N
// Property: placeTrayStoryTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceTrayStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceTrayStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceTrayStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceTrayStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeProfileStoryTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceProfileStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceProfileStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceProfileStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceProfileStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeTrayImpressedCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayImpressedGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayImpressedGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceTrayImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceTrayImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceTrayImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceTrayImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeTrayTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceTrayTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceTrayTapGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceTrayTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceTrayTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceTrayTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceTrayTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceTrayTapAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeContextCardViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceContextCardViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceContextCardViewGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceContextCardViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceContextCardViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceContextCardViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceContextCardViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceContextCardViewAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeMapImpressedCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceMapImpressedGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceMapImpressedGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceMapImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceMapImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceMapImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceMapImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceMapImpressedAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeActionCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceActionGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceActionGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeIntentionalActionCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderFemalePlaceIntentionalActionGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: genderMalePlaceIntentionalActionGenderCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1317PlaceIntentionalActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age1820PlaceIntentionalActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2124PlaceIntentionalActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age2534PlaceIntentionalActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: age35PlusPlaceIntentionalActionAgeBucketCountOneHundredEightyDays; attributes: Td,D,N
// Property: placeViewCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceViewGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceViewGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeFavoriteCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceFavoriteGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceFavoriteGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceFavoriteAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceFavoriteAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceFavoriteAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceFavoriteAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceFavoriteAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeCheckinCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceCheckinGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceCheckinGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceCheckinAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceCheckinAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceCheckinAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceCheckinAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceCheckinAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeTrayStoryViewCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeTrayStoryViewDurationSecondsOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryViewGenderDurationSecondsOneWeek; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryViewGenderDurationSecondsOneWeek; attributes: Td,D,N
// Property: age1317PlaceTrayStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age1820PlaceTrayStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age2124PlaceTrayStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age2534PlaceTrayStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: placeProfileStoryViewCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeProfileStoryViewDurationSecondsOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryViewGenderDurationSecondsOneWeek; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryViewGenderDurationSecondsOneWeek; attributes: Td,D,N
// Property: age1317PlaceProfileStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age1820PlaceProfileStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age2124PlaceProfileStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age2534PlaceProfileStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryViewAgeBucketDurationSecondsOneWeek; attributes: Td,D,N
// Property: placeTrayStoryTapCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceTrayStoryTapGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceTrayStoryTapGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceTrayStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceTrayStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceTrayStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceTrayStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceTrayStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeProfileStoryTapCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceProfileStoryTapGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceProfileStoryTapGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceProfileStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceProfileStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceProfileStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceProfileStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceProfileStoryTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeTrayImpressedCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceTrayImpressedGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceTrayImpressedGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceTrayImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceTrayImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceTrayImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceTrayImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceTrayImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeTrayTapCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceTrayTapGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceTrayTapGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceTrayTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceTrayTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceTrayTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceTrayTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceTrayTapAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeContextCardViewCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceContextCardViewGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceContextCardViewGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceContextCardViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceContextCardViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceContextCardViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceContextCardViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceContextCardViewAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeMapImpressedCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceMapImpressedGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceMapImpressedGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceMapImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceMapImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceMapImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceMapImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceMapImpressedAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeActionCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceActionGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceActionGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: placeIntentionalActionCountOneWeek; attributes: Td,D,N
// Property: genderFemalePlaceIntentionalActionGenderCountOneWeek; attributes: Td,D,N
// Property: genderMalePlaceIntentionalActionGenderCountOneWeek; attributes: Td,D,N
// Property: age1317PlaceIntentionalActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age1820PlaceIntentionalActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2124PlaceIntentionalActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age2534PlaceIntentionalActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: age35PlusPlaceIntentionalActionAgeBucketCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceViewAsTopPickCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceViewAsTopPickCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceViewAsTopPickCountOneWek; attributes: Td,D,N
// Property: mapsPlaceMapImpressedAsTopPickCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceMapImpressedAsTopPickCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceMapImpressedAsTopPickCountOneWek; attributes: Td,D,N
// Property: mapsPlaceActionsAsTopPickCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceActionsAsTopPickCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceActionsAsTopPickCountOneWek; attributes: Td,D,N
// Property: mapsPlaceIntentionalActionsAsTopPickCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceIntentionalActionsAsTopPickCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceIntentionalActionsAsTopPickCountOneWek; attributes: Td,D,N
// Property: isPlaceFromFoodCreator; attributes: TB,D,N
// Property: taRating; attributes: Td,D,N
// Property: taNumReviews; attributes: Tq,D,N
// Property: taNumCurrentReviews; attributes: Tq,D,N
// Property: taNumPhotos; attributes: Tq,D,N
// Property: hasYextPhotos; attributes: Tq,D,N
// Property: hasTaURL; attributes: Tq,D,N
// Property: taPriceyness; attributes: Tq,D,N
// Property: mapsPlaceQuadViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadViewCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadViewCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadFavoriteCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadFavoriteCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadFavoriteCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadCheckinCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadCheckinCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadCheckinCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryViewCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryViewCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryViewCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryViewCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryViewCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryTapCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadTrayStoryTapCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryTapCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadProfileStoryTapCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadTrayImpressedCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadTrayImpressedCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadTrayImpressedCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadTrayTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadTrayTapCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadTrayTapCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadContextCardTapCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadContextCardTapCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadContextCardTapCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadMapImpressedCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadMapImpressedCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadMapImpressedCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadActionCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadActionCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadActionCountOneWeek; attributes: Td,D,N
// Property: mapsPlaceQuadIntentionalActionCountOneHundredEightyDays; attributes: Td,D,N
// Property: mapsPlaceQuadIntentionalActionCountFourWeeks; attributes: Td,D,N
// Property: mapsPlaceQuadIntentionalActionCountOneWeek; attributes: Td,D,N

// +[VRZCandidatePlace descriptor]
// Type encoding: @16@0:8
// Implementation: 0x106f1ee38

@end
