// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCAListUpdate
// Superclass: SCAUserTrackedEvent
// Address: 0x112d17198

@interface SCAListUpdate


// -[SCAListUpdate getEventName]
// Type encoding: @16@0:8
// Implementation: 0x10bac996c

// -[SCAListUpdate getEventQoS]
// Type encoding: q16@0:8
// Implementation: 0x10bac9978

// -[SCAListUpdate setListGroupCount:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9980

// -[SCAListUpdate setListIds:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9998

// -[SCAListUpdate setListSnapchatterCount:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac99b0

// -[SCAListUpdate setListUpdateType:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac99c8

// -[SCAListUpdate setListWasAutogenerated:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bac99e0

// -[SCAListUpdate setSendtoSessionId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9a34

// -[SCAListUpdate setListActions:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9a4c

// -[SCAListUpdate setRecipientActions:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9a94

// -[SCAListUpdate prepareDictionary:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bac9adc

// -[SCAListUpdate getFieldNumberToFieldDict]
// Type encoding: @16@0:8
// Implementation: 0x10bac9d84

// -[SCAListUpdate toProtoWithAllowedFields:]
// Type encoding: @24@0:8@16
// Implementation: 0x10bac9d88

// -[SCAListUpdate getPayloadIdentifier]
// Type encoding: q16@0:8
// Implementation: 0x10bac9d94

@end
