// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCSnapKitCreativeKitWebAutogeneratedStickerViewModel
// Superclass: NSObject
// Address: 0x112ae8318

@interface SCSnapKitCreativeKitWebAutogeneratedStickerViewModel

// Property: thumbnailImage; attributes: T@"UIImage",R,C,N,V_thumbnailImage
// Property: title; attributes: T@"NSString",R,C,N,V_title
// Property: faviconImage; attributes: T@"UIImage",R,C,N,V_faviconImage
// Property: attribution; attributes: T@"NSString",R,C,N,V_attribution
// Property: attachmentURLString; attributes: T@"NSString",R,C,N,V_attachmentURLString

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel initWithMetadata:imageSourceProvider:attachmentURLString:]
// Type encoding: @40@0:8@16@24@32
// Implementation: 0x1065ccf34

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel generateStickerImageWithCompletion:]
// Type encoding: v24@0:8@?16
// Implementation: 0x1065cd0c4

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel fetchImagesWithCompletion:]
// Type encoding: v24@0:8@?16
// Implementation: 0x1065cd304

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel fetchThumbnailImageWithCompletion:]
// Type encoding: v24@0:8@?16
// Implementation: 0x1065cd4a0

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel fetchFaviconImageWithCompletion:]
// Type encoding: v24@0:8@?16
// Implementation: 0x1065cd608

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel thumbnailImage]
// Type encoding: @16@0:8
// Implementation: 0x1065cd868

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel title]
// Type encoding: @16@0:8
// Implementation: 0x1065cd870

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel faviconImage]
// Type encoding: @16@0:8
// Implementation: 0x1065cd878

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel attribution]
// Type encoding: @16@0:8
// Implementation: 0x1065cd880

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel attachmentURLString]
// Type encoding: @16@0:8
// Implementation: 0x1065cd888

// -[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x1065cd890

// +[SCSnapKitCreativeKitWebAutogeneratedStickerViewModel imageWithView:]
// Type encoding: @24@0:8@16
// Implementation: 0x1065cd770

@end
