// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCSnapKitCreativeKitWebAutogeneratedStickerView
// Superclass: UIView
// Address: 0x112ae82c8

@interface SCSnapKitCreativeKitWebAutogeneratedStickerView


// -[SCSnapKitCreativeKitWebAutogeneratedStickerView initWithViewModel:]
// Type encoding: @24@0:8@16
// Implementation: 0x1065cb9ac

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView setupStickerView]
// Type encoding: v16@0:8
// Implementation: 0x1065cba48

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView addThumbnailView]
// Type encoding: v16@0:8
// Implementation: 0x1065cbfac

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView addTitleView]
// Type encoding: v16@0:8
// Implementation: 0x1065cc454

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView addAttributionView]
// Type encoding: v16@0:8
// Implementation: 0x1065cc830

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView cardView]
// Type encoding: @16@0:8
// Implementation: 0x1065cce48

// -[SCSnapKitCreativeKitWebAutogeneratedStickerView .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x1065ccee4

@end
