// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: EngagementFeatures
// Superclass: GPBMessage
// Address: 0x112c40490

@interface EngagementFeatures

// Property: chatTimeSpent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasChatTimeSpent; attributes: TB,D,N
// Property: normalizedNumChatsSentViaGroup; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNormalizedNumChatsSentViaGroup; attributes: TB,D,N
// Property: normalizedNumSnapsSentViaGroup; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNormalizedNumSnapsSentViaGroup; attributes: TB,D,N
// Property: num1To1ChatsSent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasNum1To1ChatsSent; attributes: TB,D,N
// Property: num1To1SnapsSent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasNum1To1SnapsSent; attributes: TB,D,N
// Property: num1ToManyChatsSent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasNum1ToManyChatsSent; attributes: TB,D,N
// Property: num1ToManySnapsSent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasNum1ToManySnapsSent; attributes: TB,D,N
// Property: numBitmojiStickersSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumBitmojiStickersSent; attributes: TB,D,N
// Property: numChatsSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumChatsSent; attributes: TB,D,N
// Property: numChatSaved; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumChatSaved; attributes: TB,D,N
// Property: numChatScreenshots; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumChatScreenshots; attributes: TB,D,N
// Property: numChatView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumChatView; attributes: TB,D,N
// Property: numCustomStickersSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumCustomStickersSent; attributes: TB,D,N
// Property: numHoursWithStoryStoryView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumHoursWithStoryStoryView; attributes: TB,D,N
// Property: numMemoriesShared; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumMemoriesShared; attributes: TB,D,N
// Property: numScreenshots; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumScreenshots; attributes: TB,D,N
// Property: numSnapsSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumSnapsSent; attributes: TB,D,N
// Property: numSnapReplays; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumSnapReplays; attributes: TB,D,N
// Property: numSnapScreenshots; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumSnapScreenshots; attributes: TB,D,N
// Property: numSnapView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumSnapView; attributes: TB,D,N
// Property: numStickersSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStickersSent; attributes: TB,D,N
// Property: numStoryInterstitialView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryInterstitialView; attributes: TB,D,N
// Property: numStoryInterstitialViewSkips; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryInterstitialViewSkips; attributes: TB,D,N
// Property: numStoryPlaylistExits; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExits; attributes: TB,D,N
// Property: numStorySnapsScreenshots; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsScreenshots; attributes: TB,D,N
// Property: numStorySnapsViewed; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewed; attributes: TB,D,N
// Property: numStorySnapsViewedRaw; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedRaw; attributes: TB,D,N
// Property: numStorySnapCompletions; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapCompletions; attributes: TB,D,N
// Property: numStorySnapPosts; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapPosts; attributes: TB,D,N
// Property: numStorySnapReplays; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapReplays; attributes: TB,D,N
// Property: numStorySnapReplies; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapReplies; attributes: TB,D,N
// Property: numStorySnapSkips; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapSkips; attributes: TB,D,N
// Property: numStoryStoryCompletions; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryCompletions; attributes: TB,D,N
// Property: numStoryStoryLongImp; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImp; attributes: TB,D,N
// Property: numStoryStorySkips; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySkips; attributes: TB,D,N
// Property: numStoryStoryView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryView; attributes: TB,D,N
// Property: numStoryStoryViewViaInterstitialTap; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaInterstitialTap; attributes: TB,D,N
// Property: numStoryStoryViewViaTap; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTap; attributes: TB,D,N
// Property: snapTimeSpent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasSnapTimeSpent; attributes: TB,D,N
// Property: storySnapTimeSpent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpent; attributes: TB,D,N
// Property: storyStoryLongImpTime; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStoryStoryLongImpTime; attributes: TB,D,N
// Property: totalChatAckTime; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasTotalChatAckTime; attributes: TB,D,N
// Property: totalSnapAckTime; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasTotalSnapAckTime; attributes: TB,D,N
// Property: numStoryStoryViewViaTapPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapPos0; attributes: TB,D,N
// Property: numStoryStoryViewViaTapPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapPos1To3; attributes: TB,D,N
// Property: numStoryStoryViewViaTapPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapPos4To10; attributes: TB,D,N
// Property: numStoryStoryViewViaTapPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapPosBeyond11; attributes: TB,D,N
// Property: numStoryPlaylistExitsPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsPos0; attributes: TB,D,N
// Property: numStoryPlaylistExitsPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsPos1To3; attributes: TB,D,N
// Property: numStoryPlaylistExitsPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsPos4To10; attributes: TB,D,N
// Property: numStoryPlaylistExitsPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsPosBeyond11; attributes: TB,D,N
// Property: numStorySnapsViewedPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedPos0; attributes: TB,D,N
// Property: numStorySnapsViewedPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedPos1To3; attributes: TB,D,N
// Property: numStorySnapsViewedPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedPos4To10; attributes: TB,D,N
// Property: numStorySnapsViewedPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedPosBeyond11; attributes: TB,D,N
// Property: numStoryStoryLongImpPos0To4; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPos0To4; attributes: TB,D,N
// Property: numStoryStoryLongImpPosBeyond5; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPosBeyond5; attributes: TB,D,N
// Property: storySnapTimeSpentPos0; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentPos0; attributes: TB,D,N
// Property: storySnapTimeSpentPos1To3; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentPos1To3; attributes: TB,D,N
// Property: storySnapTimeSpentPos4To10; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentPos4To10; attributes: TB,D,N
// Property: storySnapTimeSpentPosBeyond11; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentPosBeyond11; attributes: TB,D,N
// Property: numStoryStoryLongImpPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPos0; attributes: TB,D,N
// Property: numStoryStoryLongImpPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPos1To3; attributes: TB,D,N
// Property: numStoryStoryLongImpPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPos4To10; attributes: TB,D,N
// Property: numStoryStoryLongImpPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpPosBeyond11; attributes: TB,D,N
// Property: numPrivateStoryRecipientOwner; attributes: Ti,D,N
// Property: numPrivateStoryOwnerRecipient; attributes: Ti,D,N
// Property: numPrivateStorySnapReceived; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapReceived; attributes: TB,D,N
// Property: numHoursWithPrivateStoryStoryView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumHoursWithPrivateStoryStoryView; attributes: TB,D,N
// Property: numPrivateStorySnapsViewed; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapsViewed; attributes: TB,D,N
// Property: numPrivateStorySnapsViewedRaw; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapsViewedRaw; attributes: TB,D,N
// Property: numPrivateStorySnapCompletions; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapCompletions; attributes: TB,D,N
// Property: numPrivateStorySnapPosts; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapPosts; attributes: TB,D,N
// Property: numPrivateStorySnapReplays; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapReplays; attributes: TB,D,N
// Property: numPrivateStorySnapSkips; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStorySnapSkips; attributes: TB,D,N
// Property: numPrivateStoryStoryCompletions; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStoryStoryCompletions; attributes: TB,D,N
// Property: numPrivateStoryStoryLongImp; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStoryStoryLongImp; attributes: TB,D,N
// Property: numPrivateStoryStorySkips; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStoryStorySkips; attributes: TB,D,N
// Property: numPrivateStoryStoryView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumPrivateStoryStoryView; attributes: TB,D,N
// Property: privateStorySnapTimeSpent; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasPrivateStorySnapTimeSpent; attributes: TB,D,N
// Property: privateStoryStoryLongImpTime; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasPrivateStoryStoryLongImpTime; attributes: TB,D,N
// Property: numStoryStoryReplies; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryReplies; attributes: TB,D,N
// Property: numStoryStoryRepliesPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesPos0; attributes: TB,D,N
// Property: numStoryStoryRepliesPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesPos1To3; attributes: TB,D,N
// Property: numStoryStoryRepliesPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesPos4To10; attributes: TB,D,N
// Property: numStoryStoryRepliesPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesPosBeyond11; attributes: TB,D,N
// Property: storySnapReplyCharCount; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasStorySnapReplyCharCount; attributes: TB,D,N
// Property: chatsSentCharCount; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasChatsSentCharCount; attributes: TB,D,N
// Property: numAudioChatsSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumAudioChatsSent; attributes: TB,D,N
// Property: audioChatsSentDuration; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasAudioChatsSentDuration; attributes: TB,D,N
// Property: numMediaChatsSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumMediaChatsSent; attributes: TB,D,N
// Property: numStorySnapShares; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapShares; attributes: TB,D,N
// Property: numStorySnapSharesSent; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapSharesSent; attributes: TB,D,N
// Property: numStorySnapSharesView; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapSharesView; attributes: TB,D,N
// Property: numStoryStoryShares; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryShares; attributes: TB,D,N
// Property: numStoryStorySharesPos0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesPos0; attributes: TB,D,N
// Property: numStoryStorySharesPos1To3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesPos1To3; attributes: TB,D,N
// Property: numStoryStorySharesPos4To10; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesPos4To10; attributes: TB,D,N
// Property: numStoryStorySharesPosBeyond11; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStoryStoryViewViaTap; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryViewViaTap; attributes: TB,D,N
// Property: numHoursWithStoryStoryViewViaTapPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryViewViaTapPos0; attributes: TB,D,N
// Property: numHoursWithStoryStoryViewViaTapPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryViewViaTapPos1To3; attributes: TB,D,N
// Property: numHoursWithStoryStoryViewViaTapPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryViewViaTapPos4To10; attributes: TB,D,N
// Property: numHoursWithStoryStoryViewViaTapPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryViewViaTapPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStoryStoryLongImp; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryLongImp; attributes: TB,D,N
// Property: numHoursWithStoryStoryLongImpPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryLongImpPos0; attributes: TB,D,N
// Property: numHoursWithStoryStoryLongImpPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryLongImpPos1To3; attributes: TB,D,N
// Property: numHoursWithStoryStoryLongImpPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryLongImpPos4To10; attributes: TB,D,N
// Property: numHoursWithStoryStoryLongImpPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryLongImpPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStoryStoryPlaylistExit; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryPlaylistExit; attributes: TB,D,N
// Property: numHoursWithStoryStoryPlaylistExitPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryPlaylistExitPos0; attributes: TB,D,N
// Property: numHoursWithStoryStoryPlaylistExitPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryPlaylistExitPos1To3; attributes: TB,D,N
// Property: numHoursWithStoryStoryPlaylistExitPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryPlaylistExitPos4To10; attributes: TB,D,N
// Property: numHoursWithStoryStoryPlaylistExitPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryPlaylistExitPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStoryStoryReply; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryReply; attributes: TB,D,N
// Property: numHoursWithStoryStoryReplyPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryReplyPos0; attributes: TB,D,N
// Property: numHoursWithStoryStoryReplyPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryReplyPos1To3; attributes: TB,D,N
// Property: numHoursWithStoryStoryReplyPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryReplyPos4To10; attributes: TB,D,N
// Property: numHoursWithStoryStoryReplyPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryReplyPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStorySnapReply; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapReply; attributes: TB,D,N
// Property: numHoursWithStorySnapSkip; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapSkip; attributes: TB,D,N
// Property: numHoursWithStorySnapSkipPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapSkipPos0; attributes: TB,D,N
// Property: numHoursWithStorySnapSkipPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapSkipPos1To3; attributes: TB,D,N
// Property: numHoursWithStorySnapSkipPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapSkipPos4To10; attributes: TB,D,N
// Property: numHoursWithStorySnapSkipPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapSkipPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStoryStoryCompletion; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryCompletion; attributes: TB,D,N
// Property: numHoursWithStoryStoryCompletionPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryCompletionPos0; attributes: TB,D,N
// Property: numHoursWithStoryStoryCompletionPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryCompletionPos1To3; attributes: TB,D,N
// Property: numHoursWithStoryStoryCompletionPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryCompletionPos4To10; attributes: TB,D,N
// Property: numHoursWithStoryStoryCompletionPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStoryStoryCompletionPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStorySnapCompletion; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapCompletion; attributes: TB,D,N
// Property: numHoursWithStorySnapCompletionPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapCompletionPos0; attributes: TB,D,N
// Property: numHoursWithStorySnapCompletionPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapCompletionPos1To3; attributes: TB,D,N
// Property: numHoursWithStorySnapCompletionPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapCompletionPos4To10; attributes: TB,D,N
// Property: numHoursWithStorySnapCompletionPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapCompletionPosBeyond11; attributes: TB,D,N
// Property: numHoursWithStorySnapView; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapView; attributes: TB,D,N
// Property: numHoursWithStorySnapViewPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapViewPos0; attributes: TB,D,N
// Property: numHoursWithStorySnapViewPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapViewPos1To3; attributes: TB,D,N
// Property: numHoursWithStorySnapViewPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapViewPos4To10; attributes: TB,D,N
// Property: numHoursWithStorySnapViewPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithStorySnapViewPosBeyond11; attributes: TB,D,N
// Property: numHoursWithPrivateStorySnapReceived; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumHoursWithPrivateStorySnapReceived; attributes: TB,D,N
// Property: numStorySnapSkipsPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsPos0; attributes: TB,D,N
// Property: numStorySnapSkipsPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsPos1To3; attributes: TB,D,N
// Property: numStorySnapSkipsPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsPos4To10; attributes: TB,D,N
// Property: numStorySnapSkipsPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsPosBeyond11; attributes: TB,D,N
// Property: numStoryStoryCompletionsPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsPos0; attributes: TB,D,N
// Property: numStoryStoryCompletionsPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsPos1To3; attributes: TB,D,N
// Property: numStoryStoryCompletionsPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsPos4To10; attributes: TB,D,N
// Property: numStoryStoryCompletionsPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsPosBeyond11; attributes: TB,D,N
// Property: numStorySnapCompletionsPos0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsPos0; attributes: TB,D,N
// Property: numStorySnapCompletionsPos1To3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsPos1To3; attributes: TB,D,N
// Property: numStorySnapCompletionsPos4To10; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsPos4To10; attributes: TB,D,N
// Property: numStorySnapCompletionsPosBeyond11; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsPosBeyond11; attributes: TB,D,N
// Property: numChatSentUrls; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentUrls; attributes: TB,D,N
// Property: numChatSentReactions; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentReactions; attributes: TB,D,N
// Property: numChatSentImages; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentImages; attributes: TB,D,N
// Property: numChatSentVideos; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentVideos; attributes: TB,D,N
// Property: numChatSentLocations; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentLocations; attributes: TB,D,N
// Property: numChatSentGifs; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentGifs; attributes: TB,D,N
// Property: numChatSentTexts; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentTexts; attributes: TB,D,N
// Property: numChatSentBloops; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentBloops; attributes: TB,D,N
// Property: numChatSentVideosNoSound; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatSentVideosNoSound; attributes: TB,D,N
// Property: numSnapSentImages; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapSentImages; attributes: TB,D,N
// Property: numSnapSentVideos; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapSentVideos; attributes: TB,D,N
// Property: numSnapSentVideosNoSound; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapSentVideosNoSound; attributes: TB,D,N
// Property: numChatViewUrls; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewUrls; attributes: TB,D,N
// Property: numChatViewReactions; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewReactions; attributes: TB,D,N
// Property: numChatViewImages; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewImages; attributes: TB,D,N
// Property: numChatViewVideos; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewVideos; attributes: TB,D,N
// Property: numChatViewLocations; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewLocations; attributes: TB,D,N
// Property: numChatViewGifs; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewGifs; attributes: TB,D,N
// Property: numChatViewAudios; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewAudios; attributes: TB,D,N
// Property: numChatViewTexts; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewTexts; attributes: TB,D,N
// Property: numChatViewBloops; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewBloops; attributes: TB,D,N
// Property: numChatViewVideosNoSound; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumChatViewVideosNoSound; attributes: TB,D,N
// Property: numSnapViewImages; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapViewImages; attributes: TB,D,N
// Property: numSnapViewVideos; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapViewVideos; attributes: TB,D,N
// Property: numSnapViewVideosNoSound; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumSnapViewVideosNoSound; attributes: TB,D,N
// Property: numStoryStoryViewViaTapTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapTimeBucket0; attributes: TB,D,N
// Property: numStoryStoryViewViaTapTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapTimeBucket1; attributes: TB,D,N
// Property: numStoryStoryViewViaTapTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapTimeBucket2; attributes: TB,D,N
// Property: numStoryStoryViewViaTapTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryViewViaTapTimeBucket3; attributes: TB,D,N
// Property: numStoryPlaylistExitsTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsTimeBucket0; attributes: TB,D,N
// Property: numStoryPlaylistExitsTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsTimeBucket1; attributes: TB,D,N
// Property: numStoryPlaylistExitsTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsTimeBucket2; attributes: TB,D,N
// Property: numStoryPlaylistExitsTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryPlaylistExitsTimeBucket3; attributes: TB,D,N
// Property: numStorySnapsViewedTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedTimeBucket0; attributes: TB,D,N
// Property: numStorySnapsViewedTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedTimeBucket1; attributes: TB,D,N
// Property: numStorySnapsViewedTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedTimeBucket2; attributes: TB,D,N
// Property: numStorySnapsViewedTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStorySnapsViewedTimeBucket3; attributes: TB,D,N
// Property: storySnapTimeSpentTimeBucket0; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentTimeBucket0; attributes: TB,D,N
// Property: storySnapTimeSpentTimeBucket1; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentTimeBucket1; attributes: TB,D,N
// Property: storySnapTimeSpentTimeBucket2; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentTimeBucket2; attributes: TB,D,N
// Property: storySnapTimeSpentTimeBucket3; attributes: T@"WindowedFloatMetrics",&,D,N
// Property: hasStorySnapTimeSpentTimeBucket3; attributes: TB,D,N
// Property: numStoryStoryLongImpTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpTimeBucket0; attributes: TB,D,N
// Property: numStoryStoryLongImpTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpTimeBucket1; attributes: TB,D,N
// Property: numStoryStoryLongImpTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpTimeBucket2; attributes: TB,D,N
// Property: numStoryStoryLongImpTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryLongImpTimeBucket3; attributes: TB,D,N
// Property: numStoryStoryRepliesTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesTimeBucket0; attributes: TB,D,N
// Property: numStoryStoryRepliesTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesTimeBucket1; attributes: TB,D,N
// Property: numStoryStoryRepliesTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesTimeBucket2; attributes: TB,D,N
// Property: numStoryStoryRepliesTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStoryRepliesTimeBucket3; attributes: TB,D,N
// Property: numStoryStorySharesTimeBucket0; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesTimeBucket0; attributes: TB,D,N
// Property: numStoryStorySharesTimeBucket1; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesTimeBucket1; attributes: TB,D,N
// Property: numStoryStorySharesTimeBucket2; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesTimeBucket2; attributes: TB,D,N
// Property: numStoryStorySharesTimeBucket3; attributes: T@"WindowedIntMetrics",&,D,N
// Property: hasNumStoryStorySharesTimeBucket3; attributes: TB,D,N
// Property: numStorySnapSkipsTimeBucket0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsTimeBucket0; attributes: TB,D,N
// Property: numStorySnapSkipsTimeBucket1; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsTimeBucket1; attributes: TB,D,N
// Property: numStorySnapSkipsTimeBucket2; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsTimeBucket2; attributes: TB,D,N
// Property: numStorySnapSkipsTimeBucket3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapSkipsTimeBucket3; attributes: TB,D,N
// Property: numStoryStoryCompletionsTimeBucket0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsTimeBucket0; attributes: TB,D,N
// Property: numStoryStoryCompletionsTimeBucket1; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsTimeBucket1; attributes: TB,D,N
// Property: numStoryStoryCompletionsTimeBucket2; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsTimeBucket2; attributes: TB,D,N
// Property: numStoryStoryCompletionsTimeBucket3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStoryStoryCompletionsTimeBucket3; attributes: TB,D,N
// Property: numStorySnapCompletionsTimeBucket0; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsTimeBucket0; attributes: TB,D,N
// Property: numStorySnapCompletionsTimeBucket1; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsTimeBucket1; attributes: TB,D,N
// Property: numStorySnapCompletionsTimeBucket2; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsTimeBucket2; attributes: TB,D,N
// Property: numStorySnapCompletionsTimeBucket3; attributes: T@"WindowedIntMetricsWithoutLongWindow",&,D,N
// Property: hasNumStorySnapCompletionsTimeBucket3; attributes: TB,D,N

// +[EngagementFeatures descriptor]
// Type encoding: @16@0:8
// Implementation: 0x10afbed9c

@end
