// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCSnapKitCreativeKitWebDataLoader
// Superclass: NSObject
// Address: 0x112ae8368

@interface SCSnapKitCreativeKitWebDataLoader


// -[SCSnapKitCreativeKitWebDataLoader initWithSnapTokenProvider:safeBrowsingAPI:snapProProfilesProvider:httpMetadataService:httpRequestModifier:imageSourceProvider:]
// Type encoding: @64@0:8@16@24@32@40@48@56
// Implementation: 0x1065cd92c

// -[SCSnapKitCreativeKitWebDataLoader loadDataWithAttachmentURLString:completionBlock:]
// Type encoding: v32@0:8@16@?24
// Implementation: 0x1065cda80

// -[SCSnapKitCreativeKitWebDataLoader _fetchShareMetadataWithAttachmentURLString:completionBlock:]
// Type encoding: v32@0:8@16@?24
// Implementation: 0x1065ce588

// -[SCSnapKitCreativeKitWebDataLoader _fetchShareMetadataWithAttachmentURLString:snapAccessToken:completionBlock:]
// Type encoding: v40@0:8@16@24@?32
// Implementation: 0x1065ce7f8

// -[SCSnapKitCreativeKitWebDataLoader _checkSafeBrowsingWithAttachmentURLString:completionBlock:]
// Type encoding: v32@0:8@16@?24
// Implementation: 0x1065cecbc

// -[SCSnapKitCreativeKitWebDataLoader getStickerMetadata:appStickerStyle:completion:]
// Type encoding: v40@0:8@16@24@?32
// Implementation: 0x1065cef08

// -[SCSnapKitCreativeKitWebDataLoader getAutogeneratedStickerFromMetadata:attachmentURLString:appStickerStyle:completion:]
// Type encoding: v48@0:8@16@24@32@?40
// Implementation: 0x1065cef20

// -[SCSnapKitCreativeKitWebDataLoader .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x1065cf744

// +[SCSnapKitCreativeKitWebDataLoader getStickerMetadata:appStickerStyle:httpMetadataService:httpRequestModifier:completion:]
// Type encoding: v56@0:8@16@24@32@40@?48
// Implementation: 0x1065cef40

// +[SCSnapKitCreativeKitWebDataLoader getAutogeneratedStickerFromMetadata:imageSourceProvider:attachmentURLString:appStickerStyle:completion:]
// Type encoding: v56@0:8@16@24@32@40@?48
// Implementation: 0x1065cf31c

// +[SCSnapKitCreativeKitWebDataLoader getAutogeneratedStickerFromStickerViewModel:appStickerStyle:completion:]
// Type encoding: v40@0:8@16@24@?32
// Implementation: 0x1065cf56c

@end
