// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCCreativeKitSnapMetadataBuilder
// Superclass: NSObject
// Address: 0x112c668e8

@interface SCCreativeKitSnapMetadataBuilder


// -[SCCreativeKitSnapMetadataBuilder build]
// Type encoding: @16@0:8
// Implementation: 0x10b084fcc

// -[SCCreativeKitSnapMetadataBuilder withKitPluginType:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b085088

// -[SCCreativeKitSnapMetadataBuilder withIsSpotlightPostingPermitted:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085090

// -[SCCreativeKitSnapMetadataBuilder withOAuthClientId:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085098

// -[SCCreativeKitSnapMetadataBuilder withApplicationId:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b0850d0

// -[SCCreativeKitSnapMetadataBuilder withAttachmentUrl:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085108

// -[SCCreativeKitSnapMetadataBuilder withSnapKitCreativeKitProduct:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b085140

// -[SCCreativeKitSnapMetadataBuilder withCreativeKitVersion:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085148

// -[SCCreativeKitSnapMetadataBuilder withDidDeleteAttachmentUrl:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085180

// -[SCCreativeKitSnapMetadataBuilder withDidDeleteCaption:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085188

// -[SCCreativeKitSnapMetadataBuilder withDidDeleteSticker:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085190

// -[SCCreativeKitSnapMetadataBuilder withLensId:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b085198

// -[SCCreativeKitSnapMetadataBuilder withScannableLensId:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b0851a0

// -[SCCreativeKitSnapMetadataBuilder withCreativeKitShareType:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b0851d8

// -[SCCreativeKitSnapMetadataBuilder withCreativeKitStickerType:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b0851e0

// -[SCCreativeKitSnapMetadataBuilder withHasAttachmentUrl:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b0851e8

// -[SCCreativeKitSnapMetadataBuilder withHasCaption:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b0851f0

// -[SCCreativeKitSnapMetadataBuilder withHasLens:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b0851f8

// -[SCCreativeKitSnapMetadataBuilder withTopicList:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085200

// -[SCCreativeKitSnapMetadataBuilder withIsUsingAutogeneratedSticker:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085238

// -[SCCreativeKitSnapMetadataBuilder withIsFromReactNativePlugin:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085240

// -[SCCreativeKitSnapMetadataBuilder withRequiresIdentityWebview:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b085248

// -[SCCreativeKitSnapMetadataBuilder withSnapKitSessionId:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085250

// -[SCCreativeKitSnapMetadataBuilder withDeepLinkUrl:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085288

// -[SCCreativeKitSnapMetadataBuilder withDeepLinkHandlingId:]
// Type encoding: @24@0:8q16
// Implementation: 0x10b0852c0

// -[SCCreativeKitSnapMetadataBuilder withHasLensLaunchData:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b0852c8

// -[SCCreativeKitSnapMetadataBuilder withIsDraggableSticker:]
// Type encoding: @20@0:8B16
// Implementation: 0x10b0852d0

// -[SCCreativeKitSnapMetadataBuilder withIdentifierForVendor:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b0852d8

// -[SCCreativeKitSnapMetadataBuilder withIpAddress:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085310

// -[SCCreativeKitSnapMetadataBuilder withSnapAdsId:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b085348

// -[SCCreativeKitSnapMetadataBuilder .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x10b085380

// +[SCCreativeKitSnapMetadataBuilder creativeKitSnapMetadata]
// Type encoding: @16@0:8
// Implementation: 0x10b08497c

// +[SCCreativeKitSnapMetadataBuilder creativeKitSnapMetadataFromExistingCreativeKitSnapMetadata:]
// Type encoding: @24@0:8@16
// Implementation: 0x10b084998

@end
