// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCACreativeKitSnapMetadata
// Superclass: SCAMapSerializable
// Address: 0x112d1ff78

@interface SCACreativeKitSnapMetadata


// -[SCACreativeKitSnapMetadata initWithDictionary:]
// Type encoding: @24@0:8@16
// Implementation: 0x10bb742a0

// -[SCACreativeKitSnapMetadata setOAuthClientId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75000

// -[SCACreativeKitSnapMetadata setSnapKitApplicationId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75018

// -[SCACreativeKitSnapMetadata setSnapKitAttachmentUrl:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75030

// -[SCACreativeKitSnapMetadata setSnapKitCreativeKitProduct:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb75048

// -[SCACreativeKitSnapMetadata setSnapKitCreativeKitVersion:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb750c8

// -[SCACreativeKitSnapMetadata setSnapKitDeleteAttachmentUrl:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb750e0

// -[SCACreativeKitSnapMetadata setSnapKitDeleteCaption:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75134

// -[SCACreativeKitSnapMetadata setSnapKitDeleteSticker:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75188

// -[SCACreativeKitSnapMetadata setSnapKitLensId:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb751dc

// -[SCACreativeKitSnapMetadata setSnapKitShareType:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb75230

// -[SCACreativeKitSnapMetadata setSnapKitStickerType:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb752b0

// -[SCACreativeKitSnapMetadata setSnapKitWithAttachmentUrl:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75330

// -[SCACreativeKitSnapMetadata setSnapKitWithCaption:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75384

// -[SCACreativeKitSnapMetadata setSnapKitWithLens:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb753d8

// -[SCACreativeKitSnapMetadata setSnapKitScannableLensId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb7542c

// -[SCACreativeKitSnapMetadata setKitPluginType:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb75444

// -[SCACreativeKitSnapMetadata setTopicList:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb754c4

// -[SCACreativeKitSnapMetadata setIsSpotlightPostingPermitted:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb754dc

// -[SCACreativeKitSnapMetadata setIsFromReactNativePlugin:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75530

// -[SCACreativeKitSnapMetadata setIsUsingAutogeneratedSticker:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75584

// -[SCACreativeKitSnapMetadata setRequiresIdentityWebView:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb755d8

// -[SCACreativeKitSnapMetadata setSnapKitSessionId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb7562c

// -[SCACreativeKitSnapMetadata setDeepLinkHandlingId:]
// Type encoding: v24@0:8q16
// Implementation: 0x10bb75644

// -[SCACreativeKitSnapMetadata setDeepLinkUrl:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75698

// -[SCACreativeKitSnapMetadata setHasLensLaunchData:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb756b0

// -[SCACreativeKitSnapMetadata setIsDraggableSticker:]
// Type encoding: v20@0:8B16
// Implementation: 0x10bb75704

// -[SCACreativeKitSnapMetadata setIdentifierForVendor:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75758

// -[SCACreativeKitSnapMetadata setIpAddress:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75770

// -[SCACreativeKitSnapMetadata setSnapAdsId:]
// Type encoding: v24@0:8@16
// Implementation: 0x10bb75788

// -[SCACreativeKitSnapMetadata getFieldNumberToFieldDict]
// Type encoding: @16@0:8
// Implementation: 0x10bb757a0

// -[SCACreativeKitSnapMetadata toProtoWithAllowedFields:]
// Type encoding: @24@0:8@16
// Implementation: 0x10bb757a4

// -[SCACreativeKitSnapMetadata getPayloadIdentifier]
// Type encoding: q16@0:8
// Implementation: 0x10bb757b0

@end
