// Objective-C runtime metadata recovered from the supplied IPA.
// Method bodies and original source files are NOT recovered here.
// Selectors, type encodings and implementation addresses follow.
#pragma once

// Runtime class: SCPreviewStickerPickerLogger
// Superclass: NSObject
// Address: 0x112a9ff28

@interface SCPreviewStickerPickerLogger

// Property: pickerOpenedCount; attributes: Tq,R,N,V_pickerOpenedCount
// Property: context; attributes: T@"NSString",C,N,V_context
// Property: hash; attributes: TQ,R
// Property: superclass; attributes: T#,R
// Property: description; attributes: T@"NSString",R,C
// Property: debugDescription; attributes: T@"NSString",?,R,C

// -[SCPreviewStickerPickerLogger initWithBlizzardServices:]
// Type encoding: @24@0:8@16
// Implementation: 0x105decffc

// -[SCPreviewStickerPickerLogger stickerPickerLoggingParametersWithMediaType:stickerTrackingCount:]
// Type encoding: @32@0:8q16q24
// Implementation: 0x105ded0e0

// -[SCPreviewStickerPickerLogger updateTappedInfoSticker:newSticker:]
// Type encoding: v32@0:8@16@24
// Implementation: 0x105ded6a8

// -[SCPreviewStickerPickerLogger logStickerAdded:isFromRecents:isFromSearch:isCreatedCustomSticker:isAutoGeneratedSticker:isFromCutout:isFromCaption:]
// Type encoding: v48@0:8@16B24B28B32B36B40B44
// Implementation: 0x105ded74c

// -[SCPreviewStickerPickerLogger listLoggingStringForSticker:]
// Type encoding: @24@0:8@16
// Implementation: 0x105dedb18

// -[SCPreviewStickerPickerLogger logStickerTracked:]
// Type encoding: v24@0:8@16
// Implementation: 0x105dedb8c

// -[SCPreviewStickerPickerLogger logStickerRemoved:isFromRecents:isCreatedCustomSticker:isFromCutout:snapSessionId:]
// Type encoding: v44@0:8@16B24B28B32@36
// Implementation: 0x105dedb9c

// -[SCPreviewStickerPickerLogger _logTrashCanDeleteForSticker:snapSessionId:]
// Type encoding: v32@0:8@16@24
// Implementation: 0x105dede4c

// -[SCPreviewStickerPickerLogger updateStickerMetricsInSnapCommonLoggingParams:]
// Type encoding: v24@0:8@16
// Implementation: 0x105dee078

// -[SCPreviewStickerPickerLogger _stickerCountOfType:]
// Type encoding: Q24@0:8Q16
// Implementation: 0x105dee8f4

// -[SCPreviewStickerPickerLogger _stickerCountFromRecentsOfType:]
// Type encoding: Q24@0:8Q16
// Implementation: 0x105dee964

// -[SCPreviewStickerPickerLogger openedStickerPicker]
// Type encoding: v16@0:8
// Implementation: 0x105dee9d4

// -[SCPreviewStickerPickerLogger closedStickerPicker:]
// Type encoding: v24@0:8q16
// Implementation: 0x105deea04

// -[SCPreviewStickerPickerLogger closedStickerPickerWithSearchCount:pretypeStickerTagSelectCount:prefixMatchStickerTagSelectCount:]
// Type encoding: v40@0:8q16q24q32
// Implementation: 0x105deea58

// -[SCPreviewStickerPickerLogger pickerOpenedCount]
// Type encoding: q16@0:8
// Implementation: 0x105deea78

// -[SCPreviewStickerPickerLogger context]
// Type encoding: @16@0:8
// Implementation: 0x105deea80

// -[SCPreviewStickerPickerLogger setContext:]
// Type encoding: v24@0:8@16
// Implementation: 0x105deea88

// -[SCPreviewStickerPickerLogger .cxx_destruct]
// Type encoding: v16@0:8
// Implementation: 0x105deea90

@end
